export enum EventsEnum {
    GET_SOCKET_ID = 'get_socket_id',
    CREATE_CHAT = 'create_chat',
    CREATE_MESSAGE = 'create_message',
    JOIN_CHAT = 'join_chat',
    CHAT_COUNT_ONLINE = 'chat_count_online',
    PONG = 'pong',
    PING = 'ping',
    VERIFY = 'verify',
    MAX_USERS_ONLINE = 'max_users_online',
    VIDEO_CALL_STARTED = 'video_call_started',
    VIDEO_CALL_JOINED = 'video_call_joined',
    VIDEO_CALL_LEFT = 'video_call_left',
    VIDEO_CALL_ENDED = 'video_call_ended',
}
